language: node_js
dist: trusty
node_js:
- '10'
- '8'
- '6'

before_install:
- sudo pip install futoin-cid
script:
- rm -rf node_modules
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test
